version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
    depends_on:
      - post_db
    image: ui:1.0

  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - front_net
      - back_net
    image: post:1.0


  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - front_net
      - back_net
    image: comment:1.0


volumes:
  post_db:

networks:
    front_net:
        driver: bridge
    back_net:
        driver: bridge


